apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: a-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: akash.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: akash-service
                port:
                  number: {{ .Values.service.port }}
